services:
  postgresreviewdl:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres_reviewdl:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: psw
      POSTGRES_USER: root
      POSTGRES_DB: sittingspots
  reviewdatalayer:
    image: sittingspotapp/reviewdatalayer:1.2-dev
    depends_on:
      - postgresreviewdl
    environment:
      HIBERNATE_DDL: create-drop
      POSTGRES_ADDRESS: jdbc:postgresql://postgresreviewdl:5432/sittingspots
      POSTGRES_USER: root
      POSTGRES_PASSWORD: psw
    ports:
      - 8083:8080