services:
  reviewprocesslayer:
    image: sittingspotapp/reviewprocesslayer:1.3-dev
    environment:
      REVIEW_DL_URL: reviewdatalayer:8080/api/v1
      SEARCH_ADAPTER_URL: searchadapter:8080/api/v1
      TAG_EXTRACTOR_URL: tagextractor:8080/api/v1
      MODERATION_URL: moderationservice:8080/api/v1
    ports:
      - 8084:8080