services:
  searchservice:
    image: sittingspotapp/searchservice:1.3-dev
    environment:
      QUERY_OPTIMIZER_URL: queryoptimizer:8080/api/v1
      SEARCH_ADAPTER_URL: searchadapter:8080/api/v1
    ports:
      - 8087:8080